### ISSUE TITLE
Errors when compiling

### ISSUE THREAD

**Issue by godreborn** [ps2dev/ps2sdk-ports#110]
I'm not sure what's causing this, but this happens quite a ways into compiling the ports:

/usr/local/ps2dev/ee/lib/gcc/mips64r5900el-ps2-elf/11.3.0/../../../../mips64r5900el-ps2-elf/bin/ld: cannot find -lcdvd: No such file or directory
/usr/local/ps2dev/ee/lib/gcc/mips64r5900el-ps2-elf/11.3.0/../../../../mips64r5900el-ps2-elf/bin/ld: cannot find -lcdvd: No such file or directory
/usr/local/ps2dev/ee/lib/gcc/mips64r5900el-ps2-elf/11.3.0/../../../../mips64r5900el-ps2-elf/bin/ld: cannot find -lpthreadglue: No such file or directory
/usr/local/ps2dev/ee/lib/gcc/mips64r5900el-ps2-elf/11.3.0/../../../../mips64r5900el-ps2-elf/bin/ld: cannot find -lcglue: No such file or directory
/usr/local/ps2dev/ee/lib/gcc/mips64r5900el-ps2-elf/11.3.0/../../../../mips64r5900el-ps2-elf/bin/ld: cannot find -lkernel: No such file or directory
collect2: error: ld returned 1 exit status
make[1]: *** [makefile:123: lua] Error 1
make[1]: Leaving directory '/home/godreborn/ps2sdk-ports/lua'
make: *** [Makefile:54: lua] Error 2

**Comment by fjtrujy** [comment]
This error happens to you because you probably were manually compiling `ps2sdk-ports` manually, and you forgot to create some symbolic links from `ps2sdk`

https://github.com/ps2dev/ps2dev/blob/master/scripts/002-ps2sdk.sh#L32-L37

My recommendation is unless you fully know the changes from the last time you compiled the toolchain, to do a clean installation following the steps from [`ps2dev/ps2dev`](https://github.com/ps2dev/ps2dev) repo.

Cheers
