### ISSUE TITLE
SDL ports don't use $GSKIT

### ISSUE THREAD

**Issue by FallenAvatar** [ps2dev/ps2sdk-ports#4]
all the makefiles are "hardcoded" to "$PS2DEV/gsKit/..." instead of $GSKIT

**Comment by sp193** [comment]
The problem is that GSKIT is not a "standard" environmental variable. If we want to standardize the use of $GSKIT, then gsKit itself must require and use it.
Currently, a number of homebrew software already assume that gsKit is installed in the "standard" location of $PS2DEV/gsKit.

**Comment by tjmonk15** [comment]
Understood. But it should be easy to use $GSKIT if available, and default it to $PS2DEV/gsKit if its not defined right?

**Comment by sp193** [comment]
Honestly, I feel that it over-complicates things. Why not just introduce the use of this variable within gsKit? Encourage developers to use $GSKIT in all new developments, and I'm sure that the problem will take care of itself.
That should be done first, before any changes are done to the software that use it (i.e. the libraries under ps2sdk-ports).

Since gsKit won't be moved, old software that assume that it's located under $PS2DEV/gsKit will still build correctly.

**Comment by AKuHAK** [comment]
Related to #24 I changed all instances to use $GSKIT, first - it is easier to check for depndency existence, second - it is not possible to install gskit without settings this variable in path.
