### ISSUE TITLE
Useful tool for Path 2 rendering

### ISSUE THREAD

**Issue by ADormant** [ps2dev/ps2sdk-ports#6]
I found a very useful tool that may be worthwile to fork and merge to ps2dev projects.

http://glampert.com/2016/01-22/q2ps2-hardware-accelerated-vertex-xform/
https://github.com/jsvennevid/openvcl
http://ps2linux.no-ip.info/playstation2-linux.com/softwaremap/trove_list0e44.html?form_cat=110
http://ps2-linux.tensioncore.com/softwaremap/trove_list53d4.html?form_cat=135

**Comment by sp193** [comment]
ps2sdk-ports contains ports of various libraries for the PlayStation 2. Since OpenVCL is a development tool, it should probably either go into the PS2SDK or be a related (and recommended) project.

That being said, I think that this conversation should continue in your other issue thread within the ps2sdk repository. If anyone else thinks that this should be here instead, please feel free to re-open this issue.
